name: Build and push frontend image to ACR

on:
  # Manual run from GitHub Actions tab.
  workflow_dispatch:
  # Push trigger is commented because this practical should run manually only.
  # push:
  #   branches: [main]

permissions:
  id-token: write
  contents: read

env:
  RESOURCE_GROUP: CIA-MEGHA-RG-01
  ACR_NAME: q1acr
  IMAGE_NAME: aca-order-frontend

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Azure login using OIDC
        uses: azure/login@v2
        with:
          client-id: ${{ secrets.AZURE_CLIENT_ID }}
          tenant-id: ${{ secrets.AZURE_TENANT_ID }}
          subscription-id: ${{ secrets.AZURE_SUBSCRIPTION_ID }}

      - name: Build and push frontend image to ACR
        uses: azure/cli@v2
        with:
          inlineScript: |
            az acr build \
              --registry ${{ env.ACR_NAME }} \
              --resource-group ${{ env.RESOURCE_GROUP }} \
              --image ${{ env.IMAGE_NAME }}:v${{ github.run_number }} \
              .
